spring:
  profiles:
    active: local
  application:
    name: ai-code-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code
    username: root
    password: ewq/.,321hf/.,

server:
  port: 3399
  servlet:
   context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.hf.aicodebackend.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# langchain4j
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
      response-format: json-object
      strict-json-schema: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true


